config/routes.rb
Cupom::Application.routes.draw do
  

  resources :termo_usos

  resources :empresas

  get "meuperfil/index"

  get "meuscupons/index"

  get "indique/index"

  get "parceiro/index"

  get "anunciantes/index"

  get "termos/index"

  get "duvidas/index"

  get "comofunciona/index"

  
 
  
  match 'auth/failure', to: redirect('/')

  devise_scope :user do
  
  get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session

  get 'sign_up', :to => 'devise/registrations#new', :as => :new_user_registration

  get 'users/sign_up', :to => 'devise/registrations#new', :as => :new_user_registration
  
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  
  end
  

  get "/ver_cupom/:id_cupom" => "portal#show", :as => :ver_cupom
  get "/ver_cupom/baixar/:id_cupom" => "portal#baixar", :as => :baixar
  get "/imprimir_cupom/:id_cupom" => "portal#imprimir", :as => :imprimir_cupom
  
  devise_for :users, :controllers => { :registrations => 'registrations',
                                       :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :offers

  resources :cities

  resources :categories

  root :to => 'portal#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/acabando.rb
class Acabando < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :offers

  attr_accessible :name_category, :category_id
  
  def to_s
    "#{name_category}"
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :offers
  attr_accessible :name

  def to_s
    "#{name}"
  end

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :offers
  attr_accessible :contato, :endereco, :name, :image
  has_attached_file :image, :styles => { :original => "315x220>", :medium => "300x300>", :thumb => "100x100>" ,:whiny => false}


  def to_s
    "#{name}"
  end


end

app/models/maiores.rb
class Maiores < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :category
  belongs_to :city
  belongs_to :empresa
  attr_accessible :address, :contact, :content, :count, :dicount, :final_date, :price, :rules, :start_date, :title, :category_id, :city_id, :avatar, :empresa_id, :por

  has_attached_file :avatar, :styles => { :original => "315x220>", :medium => "300x300>", :thumb => "100x100>", :whiny => false }


  # método de busca
  def self.search(search)
  if search
    where('title LIKE ?', "%#{search}%")
  else
    scoped
  end
  end

end

app/models/termo_uso.rb
class TermoUso < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :offer_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name, :id
  

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first

    unless user
      user = User.create(:name => auth.extra.raw_info.name,
                      :provider => auth.provider,
                      :uid => auth.uid,
                      :email => auth.info.email,
                      :password => Devise.friendly_token[0,20]
      )
    end
    user
  end



end

app/controllers/portal_controller.rb
# encoding: utf-8
class PortalController < ApplicationController
	def index
		 
		 @offer = Offer.paginate(:page => params[:page], :per_page => 2)

	end

	def show
			@offer = Offer.new
			@id_offer =  params[:id_cupom]
	end

	def baixouoferta(id_user,id_offer)


		@cupom = Ticket.where(:user_id => id_user, :offer_id => id_offer)



		
	end

	def imprimir
		
		@id_offer = params[:id_cupom]

		@offer = Offer.find(@id_offer)

	end

	def baixar

		

		if user_signed_in?
		# pegando o id do cupom para baixar
		@id_baixar =  params[:id_cupom]
		# id do usuario logado
		@user = current_user.id
		@baixou =  baixouoferta(@user,@id_baixar)
		if @baixou.length == 0
		# algoritmo gerando um token pra cada cupom
		@token = rand.to_s

		# inserção do ticket pro usuario

		@ticket = Ticket.new
		@ticket.offer_id = @id_baixar
		@ticket.user_id = @user
		@ticket.token = @token
		@ticket.save 

		# mensagem de ok!
		@mensagem = "O seu cupom já está em sua área restrita / Meus cupons."
		@protocolo = "O número de protocolo gerado foi: #{@token}"

	    else
	    # mando o usuario pra index,  ele ja baixou o cupom.
		redirect_to :controller=>'portal', :action => 'index'	    	
			
		end

		else

		redirect_to :controller=>'users', :action => 'sign_up' 
			
		end

		

		
	end # fim action baixar


	def maiores
	
		@offer_maiores = Offer.find(:all, :order => "dicount DESC", :limit => "10")

	end

	def busca
		 @offers = Offer.search(params[:search]).paginate(:per_page => 5, :page => params[:page])
	end

	
	def top
			
    end

    def acabando
    	
    end

    def baixados
    	
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/duvidas_helper.rb
module DuvidasHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/indique_helper.rb
module IndiqueHelper
end

app/helpers/meuperfil_helper.rb
module MeuperfilHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parceiro_helper.rb
module ParceiroHelper
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/helpers/termos_helper.rb
module TermosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/portal/baixar.html.erb
<div class="box_home">

<div style="margin-left:40px;">
 	<h2 style="color:#45a4dc; font-weight:12px;"><%= @mensagem %></h2>
 	<center><p style="font-weight:bold"><%= @protocolo %></p></center>
</div>

</div>

app/views/portal/busca.html.erb
<h1 style="color:#45a4dc;">Resultado de sua busca:</h1>

<% if @offers.length == 0 %>

<div class="box_home">

	<h3 style="color:#000;"> Não encontramos resultados com o que procurou.</h3>

</div>

<% else %>
	

<% @offers.each do |o|%>
<div class="cupom_box_home">

<div id="img_oferta">
	
	<%= image_tag o.avatar.url(:medium) %>

	<div id="badge_oferta">
		<span style="position:absolute; top:10px; left:25px;"><%= o.dicount %>%</span>
	</div>
	<p style="margin-left:5px; font-weight:bold;"><%= o.empresa.to_s %></p>
</div>
<div id="titulo_oferta">

<h1><%= o.title %></h1>
<p style="color:#45a4dc;">De: R$ <%= o.price.to_s+",00" %></p><p style="color:#000000; font-weigth:bold; font-size:20px;"> <strong> &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; Por: R$ <%= o.por.to_s+",00" %></strong></p>
<p style="margin-top:-35px; color:black;">Validade: <p style="margin-top:-35px; font-weight:bold; margin-left:5px;"><%= o.final_date.strftime("%b, %m %Y") %></p></p>
<p style="margin-top:-10px; font-size:28px; font-weight:bold; color:#45a4dc;"><%= o.count %></p>
<p style="margin-top:-5px; color:black; margin-left:10px;"> ja imprimiram este cupom</p>
<div id="ver_oferta">
	<%= link_to "Pegar cupom", ver_cupom_path(o.id) %>
</div>
</div>


</div>
<% end %>

<div id="paginacao">

<%= will_paginate @offers, :update => '#wrap' %>
</div>



<% end %>

app/views/portal/imprimir.html.erb
<div class="box_home">
	<div id="#cupom">
		<h2><%= @offer.title %></h2>
		<% 

			@ticket = Ticket.where(:user_id => current_user.id, :offer_id => @offer.id)
			@ticket.each do |t|
		 %>
		 <p>Número do cupom: <%= t.token %></p>

		 <% end %>
	</div>
<div align='right'><a href='javascript:window.print()'><img src='http://i361.photobucket.com/albums/oo57/ren3_02/Impressora.png'/></a></div>
</div>

app/views/portal/index.html.erb
<% @offer.each do |o|%>
<div class="cupom_box_home">

<div id="img_oferta">
	
	<%= image_tag o.avatar.url(:medium) %>

	<div id="badge_oferta">
		<span style="position:absolute; top:10px; left:25px;"><%= o.dicount %>%</span>
	</div>
	<p style="margin-left:5px; font-weight:bold;"><%= o.empresa.to_s %></p>
</div>
<div id="titulo_oferta">

<h1><%= o.title %></h1>
<p style="color:#45a4dc;">De: R$ <%= o.price.to_s+",00" %></p><p style="color:#000000; font-weigth:bold; font-size:20px;"> <strong> &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; Por: R$ <%= o.por.to_s+",00" %></strong></p>
<p style="margin-top:-35px; color:black;">Validade: <p style="margin-top:-35px; font-weight:bold; margin-left:5px;"><%= o.final_date %></p></p>
<p style="margin-top:-10px; font-size:28px; font-weight:bold; color:#45a4dc;"><%= o.count %></p>
<p style="margin-top:-5px; color:black; margin-left:10px;"> ja imprimiram este cupom</p>
<div id="ver_oferta">
	<%= link_to "Pegar cupom", ver_cupom_path(o.id) %>
</div>
</div>


</div>
<% end %>

<div id="paginacao">
<% page_entries_info @offer %>
<%= will_paginate @offer, :update => '#wrap', :next_label => 'Próxima', :previous_label => 'Anterior' %>
</div>

app/views/portal/maiores.html.erb
<% @offer_maiores.each do |o|%>
<div class="cupom_box_home">

<div id="img_oferta">
	
	<%= image_tag o.avatar.url(:medium) %>

	<div id="badge_oferta">
		<span style="position:absolute; top:10px; left:25px;"><%= o.dicount %>%</span>
	</div>
	<p style="margin-left:5px; font-weight:bold;"><%= o.empresa.to_s %></p>
</div>
<div id="titulo_oferta">

<h1><%= o.title %></h1>
<p style="color:#45a4dc;">De: R$ <%= o.price.to_s+",00" %></p><p style="color:#000000; font-weigth:bold; font-size:20px;"> <strong> &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; Por: R$ <%= o.por.to_s+",00" %></strong></p>
<p style="margin-top:-35px; color:black;">Validade: <p style="margin-top:-35px; font-weight:bold; margin-left:5px;"><%= o.final_date.strftime("%b, %m %Y") %></p></p>
<p style="margin-top:-10px; font-size:28px; font-weight:bold; color:#45a4dc;"><%= o.count %></p>
<p style="margin-top:-5px; color:black; margin-left:10px;"> ja imprimiram este cupom</p>
<div id="ver_oferta">
	<%= link_to "Pegar cupom", ver_cupom_path(o.id) %>
</div>
</div>


</div>
<% end %>

app/views/portal/show.html.erb
<div class="box_home">
	<% 
		# instanciando o objeto cupom para mostra-lo ao usuario
		
		@offer = Offer.find(@id_offer)

	 %>

     <h1 style="color:#45a4dc; font-size:20px;"><%= @offer.title %></h1>
     <br />
     <div style="float:right; width:410px; height:210px; padding-left:10px; background:#F8F8F8;">

     	<div style="">
     		
     		<div style="width:64px; height:64px; ">
     			<img src="/images/clock.png">
     		</div>
     		<h3 style="">de: R$<%= @offer.price %></h3>
     	
     		<h1 style="color:#45a4dc; margin-top:-20px; font-weight:bold; font-size:48px;">por: R$<%= @offer.por %>,00</h1>
     		<span style="font-weight:bold;">Início: <%= @offer.start_date.strftime("%b, %m %Y") %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>Fim: <%= @offer.final_date.strftime("%b, %m %Y") %></span></span>

     	</div>

     </div>
     
     <%= image_tag @offer.avatar.url %>
     <br /><br />
     <div style="background:#F8F8F8; padding:10px;">
     <h4 style="color:#45a4dc;">Descrição do cupom:</h4>
     <p> <%= @offer.content%> </p>
     </div>
     <div style="background:#F8F8F8; padding:10px;">
     <h4 style="color:#45a4dc;">Regras para utilizar este cupom:</h4>    
     <p><%= @offer.rules %></p>
     </div>
     <div style="background:#F8F8F8; padding:10px;">
     <h3 style="color:#45a4dc;">Empresa:</h3>
     <div style="width:100%;">
     <p><%= image_tag @offer.empresa.image.url %></p>
     <p style="font-weight:bold;"><%= @offer.empresa.name %></p>
     <p>Endereço: <%= @offer.empresa.endereco %></p>
      <p>Contato: <%= @offer.empresa.contato %></p>
     <p><iframe width="725" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.br/maps?f=q&amp;source=s_q&amp;hl=pt&amp;geocode=&amp;q=Rua+Alencarliense+Alves,+Campo+Grande+-+Mato+Grosso+do+Sul&amp;aq=1&amp;oq=rua+alencar&amp;sll=-20.875572,-54.261694&amp;sspn=1.588489,2.90863&amp;ie=UTF8&amp;hq=&amp;hnear=R.+Alencarliense+Alves+-+Maria+Aparecida,+Campo+Grande+-+Mato+Grosso+do+Sul,+79044-350&amp;t=m&amp;z=14&amp;ll=-20.467526,-54.550856&amp;output=embed"></iframe><br /></p>
     </div>
     <hr><br />
          <div class="fb-like" data-href="https://www.facebook.com/pages/Traz-Cupom/452678541492507?ref=hl" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true" data-font="verdana">
     </div><br /><br /><br />
     <%= link_to "Baixar Cupom", baixar_path(@offer.id), :style => "width:250px; text-decoration:none; color:white; background:#45a4dc; height:30px; padding:11px;" %>
     <br>
     <br>     
  
     </div>

</div>