config/routes.rb
Cupom::Application.routes.draw do
  

  resources :termo_usos

  resources :empresas

  get "meuperfil/index"

  get "meuscupons/index"

  get "indique/index"

  get "parceiro/index"

  get "anunciantes/index"

  get "termos/index"

  get "duvidas/index"

  get "comofunciona/index"

  
 
  
  match 'auth/failure', to: redirect('/')

  devise_scope :user do
  
  get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session

  get 'sign_up', :to => 'devise/registrations#new', :as => :new_user_registration

  get 'users/sign_up', :to => 'devise/registrations#new', :as => :new_user_registration
  
  get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  
  end
  

  get "/ver_cupom/:id_cupom" => "portal#show", :as => :ver_cupom
  get "/ver_cupom/baixar/:id_cupom" => "portal#baixar", :as => :baixar
  get "/imprimir_cupom/:id_cupom" => "portal#imprimir", :as => :imprimir_cupom
  
  devise_for :users, :controllers => { :registrations => 'registrations',
                                       :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :offers

  resources :cities

  resources :categories

  root :to => 'portal#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/acabando.rb
class Acabando < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_many :offers

  attr_accessible :name_category, :category_id
  
  def to_s
    "#{name_category}"
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :offers
  attr_accessible :name

  def to_s
    "#{name}"
  end

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :offers
  attr_accessible :contato, :endereco, :name, :image
  has_attached_file :image, :styles => { :original => "315x220>", :medium => "300x300>", :thumb => "100x100>" ,:whiny => false}


  def to_s
    "#{name}"
  end


end

app/models/maiores.rb
class Maiores < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :category
  belongs_to :city
  belongs_to :empresa
  attr_accessible :address, :contact, :content, :count, :dicount, :final_date, :price, :rules, :start_date, :title, :category_id, :city_id, :avatar, :empresa_id, :por

  has_attached_file :avatar, :styles => { :original => "315x220>", :medium => "300x300>", :thumb => "100x100>", :whiny => false }


  # método de busca
  def self.search(search)
  if search
    where('title LIKE ?', "%#{search}%")
  else
    scoped
  end
  end

end

app/models/termo_uso.rb
class TermoUso < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :offer_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name, :id
  

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first

    unless user
      user = User.create(:name => auth.extra.raw_info.name,
                      :provider => auth.provider,
                      :uid => auth.uid,
                      :email => auth.info.email,
                      :password => Devise.friendly_token[0,20]
      )
    end
    user
  end



end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new
    @offer = Offer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(params[:offer])

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/duvidas_helper.rb
module DuvidasHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/indique_helper.rb
module IndiqueHelper
end

app/helpers/meuperfil_helper.rb
module MeuperfilHelper
end

app/helpers/meuscupons_helper.rb
module MeuscuponsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parceiro_helper.rb
module ParceiroHelper
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/helpers/termos_helper.rb
module TermosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer, :html => { :multipart => true }) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :rules %><br />
    <%= f.text_area :rules %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
    <div class="field">
    <%= f.label :empresa %><br />
    <%= f.collection_select :empresa_id, Empresa.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :por %><br />
    <%= f.text_field :por %>
  </div>
  <div class="field">
    <%= f.label :dicount %><br />
    <%= f.text_field :dicount %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name_category %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.collection_select :city_id, City.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :count %><br />
    <%= f.text_field :count %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :final_date %><br />
    <%= f.date_select :final_date %>
  </div>
    <div class="field">
    <%= f.label :imagem %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<div class="box_home">
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>
</div>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Rules</th>
    <th>Empresa</th>
    <th>Contact</th>
    <th>Address</th>
    <th>Price</th>
    <th>Discount</th>
    <th>Category</th>
    <th>City</th>
    <th>Count</th>
    <th>Start date</th>
    <th>Final date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offers.each do |offer| %>
  <tr>
    <td><%= offer.title %></td>
    <td><%= offer.content %></td>
    <td><%= offer.rules %></td>
    <td><%= offer.contact %></td>
    <td><%= offer.empresa %></td>
    <td><%= offer.address %></td>
    <td><%= offer.price %></td>
    <td><%= offer.dicount %></td>
    <td><%= offer.category %></td>
    <td><%= offer.city %></td>
    <td><%= offer.count %></td>
    <td><%= offer.start_date %></td>
    <td><%= offer.final_date %></td>
    <td><%= link_to 'Show', offer %></td>
    <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
    <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<div class="box_home">
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @offer.title %>
</p>

<p>
  <b>Content:</b>
  <%= @offer.content %>
</p>

<p>
  <b>Rules:</b>
  <%= @offer.rules %>
</p>

<p>
  <b>Contact:</b>
  <%= @offer.contact %>
</p>
<p>
  <b>Empresa:</b>
  <%= @offer.empresa %>
</p>

<p>
  <b>Address:</b>
  <%= @offer.address %>
</p>

<p>
  <b>De:</b>
  <%= @offer.price %>
</p>
<p>
  <b>Por:</b>
  <%= @offer.por %>
</p>

<p>
  <b>Dicount:</b>
  <%= @offer.dicount %>
</p>

<p>
  <b>Category:</b>
  <%= @offer.category %>
</p>

<p>
  <b>City:</b>
  <%= @offer.city %>
</p>

<p>
  <b>Count:</b>
  <%= @offer.count %>
</p>

<p>
  <b>Start date:</b>
  <%= @offer.start_date %>
</p>

<p>
  <b>Final date:</b>
  <%= @offer.final_date %>
</p>

<p>
  <b>Imagem:</b>
  <%= image_tag @offer.avatar.url(:medium) %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

</div>